import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="fixed w-full h-full grid place-items-center">
        <h1 className="text-2xl font-bold capitalize">hello</h1>
      </main>
    </>
  );
}
