import Head from 'next/head';
import { GetServerSidePropsContext } from 'next';
import { getServerAuthSession } from '../lib/get-server-auth-session';
import { signIn } from 'next-auth/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="fixed w-full h-full items-center justify-center flex flex-col gap-8">
        <h1 className="text-3xl font-bold capitalize">hello</h1>
        <h2 className="text-2xl font-bold capitalize">Welcome to Home page</h2>
        <button
          onClick={() => signIn()}
          className="px-20 py-2 bg-purple-300 rounded-full text-white"
        >
          Sign In
        </button>
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getServerAuthSession(context);

  if (session) {
    return {
      redirect: {
        permanent: false,
        destination: '/profile',
      },
      props: {},
    };
  }

  return { props: { session } };
}
