import Head from 'next/head';
import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';
import { getServerAuthSession } from '../lib/get-server-auth-session';
import { signOut, useSession } from 'next-auth/react';

export default function Profile() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>{session?.user?.name ?? 'Profile'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="fixed w-full h-full items-center justify-center flex flex-col gap-8">
        {session?.user?.image && (
          <img
            src={session.user.image}
            className="aspect-square rounded-full"
            width="200px"
            height="200px"
            alt="profile pic"
          />
        )}
        <h1 className="text-3xl font-bold capitalize">
          hello {session?.user?.name ?? 'Lovely person'}
        </h1>
        <h2 className="text-2xl font-bold capitalize">Welcome to your profile page</h2>
        <button
          onClick={() => signOut()}
          className="px-20 py-2 bg-purple-300 rounded-full text-white"
        >
          Sign out
        </button>
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getServerAuthSession(context);

  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
      props: {},
    };
  }

  return { props: {} };
}
